### ISSUE TITLE
Remove extra header line on-the-fly for diff

### ISSUE THREAD

**Issue by kakwok** [kakwok/MonLoggerReader#7]
If we need `--diff` to work, pandas needs to figure out the data type before loading the txt.
Having an extra heading header line will force pandas to use object datatype for every column, hence spoiling the ability to do `diff`.

N.B. The usual trick[1] of removing extra header line will not work because this comes after loading the txt file, where the datatype for each column has already been set. 
[1] `df = df[df.timestamp != 'timestamp']`

**Comment by sethcooper** [comment]
fixed by PR #8
